### ISSUE TITLE
some suggestions

### ISSUE THREAD

**Issue by graywh** [rharish101/vim-config#1]
I saw a comment you made in another repo with an excerpt from your vimrc and thought you might be interested in some tips.

* `:vmap` is more than just visual mode.  It also maps in select mode.  `:h map-modes`  You probably want to use `:xmap` instead for most of those.

* you use a `FileType` autocmd for some Python settings, but then use `BufNewFile,BufRead` for `'ts'`, `'sw'`, and `'sts'` -- just use `FileType` for those in case you encounter a file that doesn't have the expected extension (e.g., filetype set by a modeline)

* https://github.com/rharish101/vim-config/blob/4fd119f79570c02c48cb9770f95fbf29090fd4ed/config/.vimrc#L89 I assume you mean "plaintex" -- you can configure the default flavor for *.tex files with a variable `:h g:tex_flavor`.  Since you're setting `filetype=tex`, I assume you want to use "latex".

* https://github.com/rharish101/vim-config/blob/4fd119f79570c02c48cb9770f95fbf29090fd4ed/config/.vimrc#L202 `:helptags` *builds* help tag files, which only needs to be done when you add or modify a help file (e.g., when updating or downloading a package)

* https://github.com/rharish101/vim-config/blob/4fd119f79570c02c48cb9770f95fbf29090fd4ed/config/.vimrc#L204 I think you meant to say "loading a colorscheme requires the colorscheme's location to already be in `'runtimepath'`"

* https://github.com/rharish101/vim-config/blob/4fd119f79570c02c48cb9770f95fbf29090fd4ed/config/.vimrc#L21 instead of setting `'ff'`, put "unix" first in `'fileformats'` to make it your default

**Comment by rharish101** [comment]
Hello there. Either I seem to have already applied these tips somehow, or they no longer apply. Curiously, I have no clue how I missed this issue in the first place (maybe I already saw it but forgot to reply?).

Anyway, this dude from the future thanks you for all the tips!
